/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dbms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author AJAY KUMAR
 */
public class sptaildist extends javax.swing.JFrame {

    /**
     * Creates new form sptaildist
     */
    public sptaildist() {
        initComponents();
         setVisible(false);
    }
    public static String st="";
    String message = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton1.setText("Nearest emission source");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 569, 348, 70));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton2.setText("emission sources (within 30 miles)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 469, 348, 64));

        jButton3.setBackground(new java.awt.Color(242, 242, 242));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 0, 51));
        jButton3.setText("3 nearest areas of emission source");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 370, 348, 63));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton4.setText("3 emssion sources near area");
        jButton4.setActionCommand("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 675, 348, 63));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Area Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 84, 45));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 100, 130, 45));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 189, 130, 45));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("City Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 189, 84, 45));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 359, 348, 379));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jButton5.setText("<-");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 26, -1, 43));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Emission source Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 165, 44));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 277, 130, 45));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\AJAY KUMAR\\Desktop\\1591914.jpg")); // NOI18N
        jLabel5.setText("jlabel");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        validate_();
        if(message.length()==0)
        {
            try{  
        	//step1 load the driver class  
        	Class.forName("oracle.jdbc.driver.OracleDriver");  
        	  
        	//step2 create  the connection object  
        	Connection con=DriverManager.getConnection("jdbc:oracle:thin:@218.248.0.7:1521:RDBMS","it20737122","vasavi");  
                 String areastr = this.jTextField1.getText();
                 String citystr = this.jTextField2.getText();
        	////step3 create the statement object  
        	//step4 execute query  
        	 String query = " SELECT /*+ordered (e esources_spidx) */ e.eid,e.esname,e.source_type FROM place p,esources e WHERE p.area_id=? AND p.city_id=?" +
                "AND sdo_nn(e.source_geo_location, p.place_geo_location,'sdo_num_res=1') = 'TRUE'";

        		      // create the mysql insert preparedstatement
        		PreparedStatement preparedStmt = con.prepareStatement(query);
                        preparedStmt.setInt(1,Integer.parseInt(areastr));
                        preparedStmt.setInt(2,Integer.parseInt(citystr));
            System.out.println(query);
            ResultSet rs=preparedStmt.executeQuery(); 
            int c=0;
            while(rs.next()){ 
                 st+="Emission Source :"+String.valueOf(++c);
                 st+="\nEmission source Id: "+String.valueOf(rs.getInt(1));
                 st+="\nEmission Source Name: "+rs.getString(2)+"\nEmission source Type: "+rs.getString(3)+"\n";
            }
            jTextArea1.setText(st);
            st="";
        	//stmt.executeQuery(query);  
        	System.out.println("Done");
		//esid+=1; 
        	  
        	//store the connection object  
        	con.close();  
        	  
        	}catch(Exception e){ 
        		System.out.println(e);
        		}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         validate_();
         String esstr1=this.jTextField3.getText();
         if (esstr1.length() < 4) {
			message = message + "emission source id cannot be less than 4 charcaters!\n";
		}
                else {
			for(char c : esstr1.replaceAll(" ", "").toCharArray()) {
				if (!(Character.isDigit(c))) {
					message = message + "emission source id can have only numbers!\n";
					break;
				}
			}
		}
         if (message.length() != 0) {
			JOptionPane.showMessageDialog(new JFrame(), message, "error", JOptionPane.ERROR_MESSAGE);
                
	}
        if(message.length()==0)
        {
            try{  
        	//step1 load the driver class  
        	Class.forName("oracle.jdbc.driver.OracleDriver");  
        	  
        	//step2 create  the connection object  
        	Connection con=DriverManager.getConnection("jdbc:oracle:thin:@218.248.0.7:1521:RDBMS","it20737122","vasavi");  
                 String areastr = this.jTextField1.getText();
                 String citystr = this.jTextField2.getText();
                 String esstr=this.jTextField3.getText();
        	////step3 create the statement object  
        	//step4 execute query  
        	 String query = "SELECT /*+ordered index(ps place_spidx) */  p.area_id, p.city_id,  p.place_name,  sdo_nn_distance (1) distance FROM esources e,place p WHERE e.eid=? "+
                         "AND sdo_nn( p.place_geo_location,e.source_geo_location, 'sdo_num_res=3', 1) = 'TRUE' ORDER BY distance";

        		      // create the mysql insert preparedstatement
        		PreparedStatement preparedStmt = con.prepareStatement(query);
                        preparedStmt.setInt(1,Integer.parseInt(esstr));
            System.out.println(query);
            ResultSet rs=preparedStmt.executeQuery(); 
            int c=0;
            while(rs.next()){ 
                 st+="Place :"+String.valueOf(++c);
                 st+="\nArea Id: "+String.valueOf(rs.getInt(1));
                 st+="\nCity Id: "+String.valueOf(rs.getInt(1));
                 st+="\nplace Name: "+rs.getString(3)+"\ndistance: "+rs.getFloat(4)+"\n\n";
            }
            if(st.length()!=0) {
                jTextArea1.setText(st);
                }
                else
                	jTextArea1.setText("No places Found");
                st="";
        	//stmt.executeQuery(query);  
        	System.out.println("Done");
		//esid+=1; 
        	  
        	//store the connection object  
        	con.close();  
        	  
        	}catch(Exception e){ 
        		System.out.println(e);
        		}
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         validate_();
        if(message.length()==0)
        {
            try{  
        	//step1 load the driver class  
        	Class.forName("oracle.jdbc.driver.OracleDriver");  
        	  
        	//step2 create  the connection object  
        	Connection con=DriverManager.getConnection("jdbc:oracle:thin:@218.248.0.7:1521:RDBMS","it20737122","vasavi");  
                 String areastr = this.jTextField1.getText();
                 String citystr = this.jTextField2.getText();
        	////step3 create the statement object  
        	//step4 execute query  
        	 String query = "SELECT /*+ordered*/ e.eid,e.esname, e.source_type FROM place p, esources e  WHERE p.area_id=? AND p.city_id=? "+
                         "AND sdo_within_distance (p.place_geo_location, e.source_geo_location,'distance = 50 unit=MILE')=  'TRUE'";

        		      // create the mysql insert preparedstatement
        		PreparedStatement preparedStmt = con.prepareStatement(query);
                        preparedStmt.setInt(1,Integer.parseInt(areastr));
                        preparedStmt.setInt(2,Integer.parseInt(citystr));
            System.out.println(query);
            ResultSet rs=preparedStmt.executeQuery(); 
            int c=0;
            while(rs.next()){ 
                 st+="Emission Source :"+String.valueOf(++c);
                 st+="\nEmission source Id: "+String.valueOf(rs.getInt(1));
                 st+="\nEmission Source Name: "+rs.getString(2)+"\nEmission source Type: "+rs.getString(3)+"\n";
            }
            if(st.length()!=0) {
            jTextArea1.setText(st);
            }
            else
            	jTextArea1.setText("No Emission Sources Found");
            st="";
        	//stmt.executeQuery(query);  
        	System.out.println("Done");
		//esid+=1; 
        	  
        	//store the connection object  
        	con.close();  
        	  
        	}catch(Exception e){ 
        		System.out.println(e);
        		}
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        validate_();
        if(message.length()==0)
        {
            try{  
        	//step1 load the driver class  
        	Class.forName("oracle.jdbc.driver.OracleDriver");  
        	  
        	//step2 create  the connection object  
        	Connection con=DriverManager.getConnection("jdbc:oracle:thin:@218.248.0.7:1521:RDBMS","it20737122","vasavi");  
                 String areastr = this.jTextField1.getText();
                 String citystr = this.jTextField2.getText();
        	////step3 create the statement object  
        	//step4 execute query  
        	 String query = "SELECT /*+ordered*/ e.eid, e.esname, e.source_type FROM place p, esources e WHERE p.area_id= ? AND p.city_id=?" +
"AND sdo_nn (e.source_geo_location, p.place_geo_location, 'sdo_num_res=3') = 'TRUE'";

        		      // create the mysql insert preparedstatement
        		PreparedStatement preparedStmt = con.prepareStatement(query);
                        preparedStmt.setInt(1,Integer.parseInt(areastr));
                        preparedStmt.setInt(2,Integer.parseInt(citystr));
            System.out.println(query);
            ResultSet rs=preparedStmt.executeQuery(); 
            int c=0;
            while(rs.next()){ 
                 st+="Emission Source :"+String.valueOf(++c);
                 st+="\nEmission source Id: "+String.valueOf(rs.getInt(1));
                 st+="\nEmission Source Name: "+rs.getString(2)+"\nEmission source Type: "+rs.getString(3)+"\n\n";
            }
            if(st.length()!=0) {
            jTextArea1.setText(st);
            }
            else
            	jTextArea1.setText("No Emission Sources Found");
            st="";
        	//stmt.executeQuery(query);  
        	System.out.println("Done");
		//esid+=1; 
        	  
        	//store the connection object  
        	con.close();  
        	  
        	}catch(Exception e){ 
        		System.out.println(e);
        		}
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    public void validate_() 
    {
                message="";
                String areastr,citystr;
		areastr = this.jTextField1.getText();
                int areaid,cityid;
                citystr=this.jTextField2.getText();
		if (areastr.length() < 4) {
			message = message + "area-id cannot be less than 4 charcaters!\n";
		}
                else {
			for(char c : areastr.replaceAll(" ", "").toCharArray()) {
				if (!(Character.isDigit(c))) {
					message = message + "Area id can have only numbers!\n";
					break;
				}
			}
		}
                if (citystr.length() < 4) {
			message = message + "city-id cannot be less than 4 charcaters!\n";
		}
                else {
			for(char c : citystr.replaceAll(" ", "").toCharArray()) {
				if (!(Character.isDigit(c))) {
					message = message + "city id can have only numbers!\n";
					break;
				}
			}
		}
                if (message.length() != 0) {
			JOptionPane.showMessageDialog(new JFrame(), message, "error", JOptionPane.ERROR_MESSAGE);
                
		}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sptaildist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sptaildist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sptaildist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sptaildist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sptaildist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
